package br.com.gcbank.view;

import br.com.gcbank.exceptions.SaldoInsuficienteException;
import br.com.gcbank.model.ContaCorrente;
import br.com.gcbank.model.Conta;
import br.com.gcbank.service.ContaService;
import java.util.ArrayList;
import static java.util.stream.Collectors.*;
import java.util.Map;
import java.util.List;




import java.io.IOException;
import java.util.Arrays;
import java.util.Comparator;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// import strategy.TarifaStrategy;

public class ContaGUI extends javax.swing.JFrame {

    /**
     * Creates new form ContaGUI
     */
    
    private ContaCorrente conta;
    private ContaService contaService;
    
    public ContaGUI() {
        this.contaService = new ContaService();
        initComponents();
        carregarDados();
        atualizarTabela();
        
        btnFixa.addActionListener(e -> aplicarTarifa(TarifaStrategy.FIXA));
        btnPercentual.addActionListener(e -> aplicarTarifa(TarifaStrategy.PERCENTUAL));
        btnIsenta.addActionListener(e -> aplicarTarifa(TarifaStrategy.ISENTA));
        
        
        TabelaContas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { 
                int index = TabelaContas.getSelectedRow();
                if (index >= 0 && index < contaService.getContas().size()) {
                    conta = contaService.getContas().get(index);
                    txtNumero.setText(String.valueOf(conta.getNumero()));
                    txtTitular.setText(conta.getTitular());
                    txtSaldo.setText("R$ " + String.format("%.2f", conta.getSaldo()));
                }
            }
        });
        
        TabelaContas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && TabelaContas.getSelectedRow() >= 0) {
                int linha = TabelaContas.getSelectedRow();
                model.ContaCorrente conta = contaService.getContas().get(linha);

                txtNumero.setText(String.valueOf(conta.getNumero()));
                txtTitular.setText(conta.getTitular());
                txtSaldo.setText("R$ " + String.format("%.2f", conta.getSaldo()));
            }
        });
    }
    
    private void aplicarTarifa(TarifaStrategy strategy) {
        List<ContaCorrente> contas = contaService.getContas();

        txtAreaArquivo.setText("\nTarifas (" + strategy + "):\n\n");

        contas.forEach(conta -> {
            double tarifa = strategy.calcular(conta.getSaldo());
            txtAreaArquivo.append(conta.getNumero() + " "
                                 + conta.getTitular() + " "
                                 + conta.getSaldo() + " -> Tarifa: "
                                 + tarifa + "\n");
        });
    }
    
    private void carregarDados() {    
        try {
            List<ContaCorrente> contas = contaService.carregarTodasContas();

            DefaultTableModel model = (DefaultTableModel) TabelaContas.getModel();
            model.setRowCount(0);

            for (ContaCorrente c : contas) {
                model.addRow(new Object[]{
                    c.getNumero(),
                    c.getTitular(),
                    String.format("R$ %.2f", c.getSaldo())
                });
            }

            if (!contas.isEmpty()) {
                ContaCorrente primeira = contas.get(0);
                TabelaContas.setRowSelectionInterval(0, 0);
                txtNumero.setText(String.valueOf(primeira.getNumero()));
                txtTitular.setText(primeira.getTitular());
                txtSaldo.setText(String.format("R$ %.2f", primeira.getSaldo()));
                txtAreaArquivo.append("Conta carregada com sucesso!\n\n");
            }

        } catch (IOException e) {
            txtAreaArquivo.append("Erro ao acessar o banco: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNumero = new javax.swing.JLabel();
        lblTitular = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtTitular = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        lblSaque = new javax.swing.JLabel();
        txtSaque = new javax.swing.JTextField();
        btnSacar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaArquivo = new javax.swing.JTextArea();
        btnDepositar = new javax.swing.JButton();
        CriarConta = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabelaContas = new javax.swing.JTable();
        FiltrarSaldo = new javax.swing.JButton();
        SaldoTotal = new javax.swing.JButton();
        AgruparFaixa = new javax.swing.JButton();
        SaldoMaiorPredicate = new javax.swing.JButton();
        OrdenarNomes = new javax.swing.JButton();
        SalarioDecrescente = new javax.swing.JButton();
        lblNumero1 = new javax.swing.JLabel();
        btnPercentual = new javax.swing.JButton();
        btnFixa = new javax.swing.JButton();
        btnIsenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        OrigemTxt = new javax.swing.JTextField();
        DestinoTxt = new javax.swing.JTextField();
        ValorTxt = new javax.swing.JTextField();
        TransferirBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BuscaNumeroTxT = new javax.swing.JTextField();
        BuscarNumeroBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        RemoverTxt = new javax.swing.JTextField();
        RemoverBtn = new javax.swing.JButton();
        ListarContasTxt = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GERENCIADOR DE CONTA BANCÁRIA");

        lblNumero.setText("Número:");

        lblTitular.setText("Titular:");

        lblSaldo.setText("Saldo:");

        lblSaque.setText("Valor para saque ou deposito:");

        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        txtAreaArquivo.setEditable(false);
        txtAreaArquivo.setColumns(20);
        txtAreaArquivo.setRows(5);
        jScrollPane1.setViewportView(txtAreaArquivo);

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        CriarConta.setText("Criar Conta");
        CriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarContaActionPerformed(evt);
            }
        });

        TabelaContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero Conta", "Nome", "Saldo"
            }
        ));
        jScrollPane4.setViewportView(TabelaContas);

        FiltrarSaldo.setText("Filtrar Saldo > 10.000");
        FiltrarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrarSaldoActionPerformed(evt);
            }
        });

        SaldoTotal.setText("Saldo Total");
        SaldoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldoTotalActionPerformed(evt);
            }
        });

        AgruparFaixa.setText("Agrupar por Faixa");
        AgruparFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgruparFaixaActionPerformed(evt);
            }
        });

        SaldoMaiorPredicate.setText("Saldo > 5.000");
        SaldoMaiorPredicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldoMaiorPredicateActionPerformed(evt);
            }
        });

        OrdenarNomes.setText("Ordenar Nomes");
        OrdenarNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarNomesActionPerformed(evt);
            }
        });

        SalarioDecrescente.setText("Salário Decrescente");
        SalarioDecrescente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioDecrescenteActionPerformed(evt);
            }
        });

        lblNumero1.setText("Tarifas:");

        btnPercentual.setText("Percentual");

        btnFixa.setText("Fixa");

        btnIsenta.setText("Isenta");

        jLabel1.setText("Tranferir Dinheiro");

        jLabel2.setText("Origem:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Destino:");

        TransferirBtn.setText("Tranferir");
        TransferirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferirBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Busca por Número: ");

        BuscaNumeroTxT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaNumeroTxTActionPerformed(evt);
            }
        });

        BuscarNumeroBtn.setText("Buscar");
        BuscarNumeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNumeroBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Remover por Número: ");

        RemoverTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverTxtActionPerformed(evt);
            }
        });

        RemoverBtn.setText("Remover");
        RemoverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverBtnActionPerformed(evt);
            }
        });

        ListarContasTxt.setText("Listar Contas");
        ListarContasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarContasTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitular)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnDepositar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CriarConta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SaldoMaiorPredicate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgruparFaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FiltrarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SaldoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OrdenarNomes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SalarioDecrescente))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnPercentual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnIsenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(OrigemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(TransferirBtn)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(DestinoTxt)
                                                .addComponent(ValorTxt))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ListarContasTxt)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 25, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RemoverTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(BuscaNumeroTxT))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuscarNumeroBtn)
                                    .addComponent(RemoverBtn))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero)
                            .addComponent(lblNumero1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitular)
                            .addComponent(btnFixa))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSaldo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnPercentual)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSaque)
                                    .addComponent(txtSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnIsenta)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDepositar)
                            .addComponent(btnSacar)
                            .addComponent(CriarConta)
                            .addComponent(ListarContasTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FiltrarSaldo)
                            .addComponent(SaldoTotal)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgruparFaixa)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(OrigemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DestinoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ValorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaldoMaiorPredicate)
                            .addComponent(OrdenarNomes))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SalarioDecrescente)
                            .addComponent(TransferirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(BuscaNumeroTxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarNumeroBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(RemoverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoverBtn))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
            try {
            double valor = Double.parseDouble(txtSaque.getText().trim());

            contaService.sacarValor(conta, valor);

            txtSaldo.setText("R$ " + String.format("%.2f", conta.getSaldo()));

            txtAreaArquivo.append(String.format("Saque de R$ %.2f realizado com sucesso.\n\n", valor));

            int linhaSelecionada = TabelaContas.getSelectedRow();
            if (linhaSelecionada >= 0) {
                TabelaContas.setValueAt(conta.getNumero(), linhaSelecionada, 0);
                TabelaContas.setValueAt(conta.getTitular(), linhaSelecionada, 1);
                TabelaContas.setValueAt("R$ " + String.format("%.2f", conta.getSaldo()), linhaSelecionada, 2);
            }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Informe um valor numérico válido para saque.",
                                              "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (SaldoInsuficienteException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(),
                                              "Saldo Insuficiente", JOptionPane.WARNING_MESSAGE);
                txtAreaArquivo.append("Tentativa de saque inválida: " + ex.getMessage() + "\n\n");
            }
            try {
                contaService.salvarContas("contas_atualizadas.txt");
                txtAreaArquivo.append("Contas salvas em contas_atualizadas.txt\n\n");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar contas: " + ex.getMessage(),
                                              "Erro", JOptionPane.ERROR_MESSAGE);
             }
    }//GEN-LAST:event_btnSacarActionPerformed

    
    
    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        try {
            double valor = Double.parseDouble(txtSaque.getText().trim());

            contaService.depositarValor(conta, valor);

            txtSaldo.setText("R$ " + String.format("%.2f", conta.getSaldo()));

            txtAreaArquivo.append(String.format("Depósito de R$ %.2f realizado com sucesso.\n\n", valor));

            int linhaSelecionada = TabelaContas.getSelectedRow();
            if (linhaSelecionada >= 0) {
                TabelaContas.setValueAt(conta.getNumero(), linhaSelecionada, 0);
                TabelaContas.setValueAt(conta.getTitular(), linhaSelecionada, 1);
                TabelaContas.setValueAt("R$ " + String.format("%.2f", conta.getSaldo()), linhaSelecionada, 2);
            }

          } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Informe um valor numérico válido para depósito.",
                                              "Erro", JOptionPane.ERROR_MESSAGE);
         }
         try {
            contaService.salvarContas("contas_atualizadas.txt");
            txtAreaArquivo.append("Contas salvas em contas_atualizadas.txt\n\n");
         } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar contas: " + ex.getMessage(),
                                          "Erro", JOptionPane.ERROR_MESSAGE);
         }

    }//GEN-LAST:event_btnDepositarActionPerformed

    private void atualizarTabela() {
         int linhaSelecionada = TabelaContas.getSelectedRow();
    DefaultTableModel model = (DefaultTableModel) TabelaContas.getModel();

    model.setRowCount(0);

    ArrayList<ContaCorrente> contas = contaService.getContas();
    for (ContaCorrente c : contas) {
        model.addRow(new Object[] {
            c.getNumero(),
            c.getTitular(),
            String.format("R$ %.2f", c.getSaldo())
        });
    }

    if (linhaSelecionada >= 0 && linhaSelecionada < model.getRowCount()) {
        TabelaContas.setRowSelectionInterval(linhaSelecionada, linhaSelecionada);
    }
}


    
    private void CriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarContaActionPerformed
       try {
        int numero = Integer.parseInt(txtNumero.getText().trim());
        String titular = txtTitular.getText().trim();

        String saldoTxt = txtSaldo.getText()
                .replace("R$", "").replace(" ", "")
                .replace(".", "").replace(",", ".").trim();
        double saldoInicial = 0.0;
        if (!saldoTxt.isEmpty()) {
            saldoInicial = Double.parseDouble(saldoTxt);
        }

        java.util.ArrayList<model.ContaCorrente> lista = contaService.getContas();
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getNumero() == numero) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Já existe uma conta com esse número.",
                        "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        model.ContaCorrente nova = new model.ContaCorrente(numero, titular, saldoInicial);
        contaService.adicionarConta(nova);

        atualizarTabela();

        int idx = contaService.getContas().size() - 1;
        if (idx >= 0 && idx < TabelaContas.getRowCount()) {
            TabelaContas.setRowSelectionInterval(idx, idx);
        }

        txtAreaArquivo.append(String.format(
                "Conta %d criada para %s com saldo inicial R$ %.2f\n",
                numero, titular, saldoInicial));
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Preencha Número (inteiro) e saldo válido.",
                    "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        txtNumero.setText("");
        txtTitular.setText("");
        txtSaldo.setText("");
        
        try {
            contaService.salvarContas("contas_atualizadas.txt");
            txtAreaArquivo.append("Contas salvas em contas_atualizadas.txt\n");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar contas: " + ex.getMessage(),
                                          "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_CriarContaActionPerformed

    private void SaldoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoTotalActionPerformed
        
        double saldoTotal = contaService.getContas().stream()
                .map(contas -> contas.getSaldo())
                .reduce(0.0, (a, b) -> a + b);
        
         txtAreaArquivo.append("Saldo Total de Todas as Contas: R$ " + String.format("%.2f", saldoTotal) + "\n\n");
    }//GEN-LAST:event_SaldoTotalActionPerformed

    private void FiltrarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrarSaldoActionPerformed
        // TODO add your handling code here:
        txtAreaArquivo.append("Contas com o saldo acima de R$ 10.000,00\n\n");
        
        contaService.getContas().stream()
                .filter(conta -> conta.getSaldo() > 10000)
                .forEach(conta -> txtAreaArquivo.append(
                        String.format("Conta %d | %s | Saldo: R$ %.2f\n",
                                conta.getNumero(), conta.getTitular(), conta.getSaldo())
                ));
    }//GEN-LAST:event_FiltrarSaldoActionPerformed

    
    private void AgruparFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgruparFaixaActionPerformed
        Map<String, List<ContaCorrente>> agruparFaixa = contaService.getContas().stream()
                .collect(groupingBy(
                        conta -> {
                            if (conta.getSaldo() <= 5000) return "Até R$5000,00";
                            else if (conta.getSaldo() <= 10000 ) return "De R$5001 até R%10000";
                            else return "Acima de R$10000";
                        }
                ));
       agruparFaixa.forEach((faixa, lista) -> {
            txtAreaArquivo.append(faixa + ":\n");
            lista.forEach(c -> txtAreaArquivo.append(
                String.format("  Conta %d | %s | R$ %.2f \n\n", c.getNumero(), c.getTitular(), c.getSaldo())
            ));
        });
    }//GEN-LAST:event_AgruparFaixaActionPerformed

    private void SaldoMaiorPredicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoMaiorPredicateActionPerformed
        txtAreaArquivo.append("\nContas com o saldo superior a R$5.000 e com número de conta Par:\n\n");
        
        Predicate<Conta> salarioMaior = s -> s.getSaldo() > 5000 && s.getNumero() % 2 == 0;
        
        List<Conta> filtrados = contaService.getContas().stream()
                .filter(salarioMaior)
                .collect(Collectors.toList());
        
        filtrados.forEach((conta) -> {
            txtAreaArquivo.append(conta.getNumero() + " " + conta.getTitular() + " " + conta.getSaldo());
        });
        
    }//GEN-LAST:event_SaldoMaiorPredicateActionPerformed

    private void OrdenarNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarNomesActionPerformed
        // TODO add your handling code here:
       Comparator<Conta> ordenacaoNomes = (t1, t2) -> t1.getTitular().compareTo(t2.getTitular());
       
       List<Conta> nomesOrdenados = contaService.getContas().stream()
               .sorted(ordenacaoNomes)
               .collect(Collectors.toList());
       
        
        txtAreaArquivo.append("\nNomes Ordenados em Ordem alfabética:\n\n");
        
        nomesOrdenados.forEach((conta) -> {
            txtAreaArquivo.append(conta.getNumero() + " " + conta.getTitular() + " " + conta.getSaldo() + "\n");
        });
    }//GEN-LAST:event_OrdenarNomesActionPerformed

    private void SalarioDecrescenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioDecrescenteActionPerformed
        Comparator<Conta> salarioDecrescente = (s1, s2) -> Double.compare(s2.getSaldo(), s1.getSaldo());
        
        List<Conta> salariosOrdenados = contaService.getContas().stream()
               .sorted(salarioDecrescente)
               .collect(Collectors.toList());
        
         txtAreaArquivo.append("\nSalários Ordenados em Ordem Decrescente:\n\n");
        
        salariosOrdenados.forEach((conta) -> {
            txtAreaArquivo.append(conta.getNumero() + " " + conta.getTitular() + " " + conta.getSaldo() + "\n");
        });
    }//GEN-LAST:event_SalarioDecrescenteActionPerformed

    private void TransferirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferirBtnActionPerformed
        try {
            int numeroOrigem = Integer.parseInt(OrigemTxt.getText().trim());
            int numeroDestino = Integer.parseInt(DestinoTxt.getText().trim());
            double valor = Double.parseDouble(ValorTxt.getText().trim());

            
            contaService.transferir(numeroOrigem, numeroDestino, valor);

            txtAreaArquivo.append("Transferência realizada com sucesso!");

            carregarDados();  

        } catch (NumberFormatException e) {
             txtAreaArquivo.append("Por favor, insira valores válidos.");
        } catch (Exception e) {
            txtAreaArquivo.append("Erro na transferência: " + e.getMessage());
            e.printStackTrace();
        } 
    }//GEN-LAST:event_TransferirBtnActionPerformed

    private void BuscarNumeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNumeroBtnActionPerformed
        try {
            int numeroBusca = Integer.parseInt(BuscaNumeroTxT.getText().trim());
            
            Conta contaEncontrada = contaService.buscarConta(numeroBusca);
            
            txtAreaArquivo.append("Conta Encontrada!:\n\n");
            txtAreaArquivo.append("Numero da Conta: " + contaEncontrada.getNumero());
            txtAreaArquivo.append("\nTitular: " + contaEncontrada.getTitular());
            txtAreaArquivo.append("\nSaldo: " + contaEncontrada.getSaldo() + "\n\n");
            
            
            carregarDados();
                    
        } catch (NumberFormatException e){
            txtAreaArquivo.append("Insira valores válidos!!");
        }
    }//GEN-LAST:event_BuscarNumeroBtnActionPerformed

    private void BuscaNumeroTxTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaNumeroTxTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscaNumeroTxTActionPerformed

    private void RemoverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverBtnActionPerformed
        try {
            int numeroRemover = Integer.parseInt(RemoverTxt.getText().trim());
            
            contaService.removerConta(numeroRemover);
            
            carregarDados();
            
            txtAreaArquivo.append("Conta do numero: " + numeroRemover + " Removida do banco de dados!");
                    
        } catch (NumberFormatException e){
            txtAreaArquivo.append("Insira valores válidos!!");
        }
        
    }//GEN-LAST:event_RemoverBtnActionPerformed

    private void RemoverTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverTxtActionPerformed

    private void ListarContasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarContasTxtActionPerformed
        try {
            List<ContaCorrente> contas = contaService.carregarTodasContas();
            
            txtAreaArquivo.append("Contas Registradas:\n\n");
            
            contas.forEach((conta) -> {     
                txtAreaArquivo.append("Numero da Conta: " + conta.getNumero());
                txtAreaArquivo.append("\nTitular: " + conta.getTitular());
                txtAreaArquivo.append("\nSaldo: " + conta.getSaldo() + "\n\n");
            });
            
        } catch (IOException e) {
            txtAreaArquivo.append("Erro ao procurar as contas!!\n\n");
        }
    }//GEN-LAST:event_ListarContasTxtActionPerformed

  

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ContaGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgruparFaixa;
    private javax.swing.JTextField BuscaNumeroTxT;
    private javax.swing.JButton BuscarNumeroBtn;
    private javax.swing.JButton CriarConta;
    private javax.swing.JTextField DestinoTxt;
    private javax.swing.JButton FiltrarSaldo;
    private javax.swing.JButton ListarContasTxt;
    private javax.swing.JButton OrdenarNomes;
    private javax.swing.JTextField OrigemTxt;
    private javax.swing.JButton RemoverBtn;
    private javax.swing.JTextField RemoverTxt;
    private javax.swing.JButton SalarioDecrescente;
    private javax.swing.JButton SaldoMaiorPredicate;
    private javax.swing.JButton SaldoTotal;
    private javax.swing.JTable TabelaContas;
    private javax.swing.JButton TransferirBtn;
    private javax.swing.JTextField ValorTxt;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnFixa;
    private javax.swing.JButton btnIsenta;
    private javax.swing.JButton btnPercentual;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaque;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JTextArea txtAreaArquivo;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSaque;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
